# -*- coding: utf-8 -*-
"""PRACTICAL3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSURs5YWn11PvzMw_19eFGV8v0b4Ms1h
"""

import time

def heapify(arr, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2

    if left < n and arr[left] > arr[largest]:
        largest = left

    if right < n and arr[right] > arr[largest]:
        largest = right

    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        heapify(arr, n, largest)


def max_heap_sort(arr):
    n = len(arr)

    # Build Max Heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    # Extract elements
    for i in range(n - 1, 0, -1):
        arr[0], arr[i] = arr[i], arr[0]
        heapify(arr, i, 0)


# User Input
arr = list(map(int, input("Enter elements separated by space: ").split()))

print("Original array:", arr)

# Calculate execution time
start_time = time.perf_counter()

max_heap_sort(arr)

end_time = time.perf_counter()

print("Sorted array:", arr)
print("Execution time:", end_time - start_time, "seconds")

print("Time Complexity:")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n log n)")
print("Space        : O(log n)")

import time

def heapify(arr, n, i):
    smallest = i
    left = 2 * i + 1
    right = 2 * i + 2

    if left < n and arr[left] < arr[smallest]:
        smallest = left

    if right < n and arr[right] < arr[smallest]:
        smallest = right

    if smallest != i:
        arr[i], arr[smallest] = arr[smallest], arr[i]
        heapify(arr, n, smallest)


def min_heap_sort(arr):
    n = len(arr)

    # Build Min Heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    # Extract elements
    for i in range(n - 1, 0, -1):
        arr[0], arr[i] = arr[i], arr[0]
        heapify(arr, i, 0)


# User Input
arr = list(map(int, input("Enter elements separated by space: ").split()))

print("Original array:", arr)

# Calculate execution time
start_time = time.perf_counter()

min_heap_sort(arr)

end_time = time.perf_counter()

print("Sorted array:", arr)
print("Execution time:", end_time - start_time, "seconds")

print("Time Complexity:")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n log n)")
print("Space        : O(log n)")